# Contexte

> Contexte (structure, projet, enjeux du projet, comment le stage s'insère dans le projet, quels acteurs sont rencontrés et quels sont leurs rôles)

## Le C.I.S.T
 Présentation de la Fédération de recherche, de sa structuration et des axes, en précisan qu'a terme je travaillerai ussi sur cers projets bien qu'ils ne fassent pas parti du stage. 

### IMAGEUN et l'ANR - DFG 
 Présenter l'objectif principal du projet, les workshops et les acteurs. En venir au **Workshop - students** surlequel je travaille dans le cadre du stage et détailler mon rôle, expliquer la Base de donnée ce qui a été mis en place avant mon arrivée (de quoi je pars) dan les grandes lignes sans entrer dans les problèmes etc...
 
 Présenter ensuite la collecte et la base de donnée générale  :
  - temporalité
  effectifs
  objectifs réalisés ou non
  
## EuroBroadMap et Glocal Map

Les résultats Europe sont très normées, voir prévisibles, tandis que d'autres pays adoptent un regard plus critique vis à vis de l'Europe. - Chine mode, luxe, sp Afrique : Tunisie et Sénégal : crique sur le racisme / inégalité / colonialisme Brésil :

## Echéances

-   15 Juin - **50 ans de l'ANR DFG** : *Production d'une "image" comprenant des cartes lissées des premiers résultats pour la France et l'allemagne ainsi que des nuages de mots décrivant l'Europe*
-   20/24 Juin - **Ecole d'Ete** : *Pas directent en lien avec le stage mais plutot avec les missions de la Fédération de recherche*
-   23/26 Juin - **Tachkent** : *Préparation des données issues des réponses turques pour la doctorante travaillant sur le projet. Il s'agissait pour elle de présenter ces résultts à une conférence avec le partenaire Turc.*
    -   Typologie des polygones
    -   Cartographie de ces polygones
    -   Nettoyage de BD et réalisation d'un dictionnaire réduit à l'usage du partenaire
    -   Production de graphiques et résultats statistiques préliminaires
-   **30 Juin : ARRET DE LA DIFFUSION DU QUESTIONNAIRE**
-   18/22 Juillet - **UGI - Congrès Centenaire de l'Union Géographique Internationale** : *Préparation des données propres et prete à etre exploitées*
    -   Typoogie des polygones restants
    -   Cartographie pour chaque pays / ville / université
    -   Graphiques pour chaque pays / ville / université
    -   ...
-   18 Septembre - **JIG Journée des jeunes chercheurs de l'institut de géographie** : *Réalisation d'un poster*

## Objectifs
Livrer une base de donnée et des traitements s'inscrivant dans la reproductibilité, mais l'arrivée de la base de donnée finale s'etant faite tardivement nous avons plutot opté pour une chaine de traitement propre, dirigée vers les besoins immédiats des acteurs (Tachkent, UGI,  mémoire). la mise en package se fera certainement dans un deuxieme temps, d'autna plus que le contrat se poursuit au dela du stage pour ces missions là (ainsi que pour de la valorisation).


Il était donc question de mettre en place des traitements de géomatiques (SIG géotraitements des géométries et données spatialisées) ainsi que des traitements textuels (cordonner notamement la traduction). 
Il a fallu dans un premier temps me familiariser avec la base de donnée avant de détecter les problèmes et d'en proposer lse corrections. 

Je suis partie d'une base de programmes ayant servis aux premieres explorations (graphiques statistiques généraux sur les taux de réponses et premières visualisation des gféométries). Mon travail a été d'améliorer et enrichir ces programmes (optimisation de la chaine de traitement, des scripts et des temps d'exécution).

*Insérer ici un graphique de la chaine de traitement finale avec un code couleur pour les anciens et nouveaux scripts)*



## Quels outils : Pour R et pas un SIG traditionnel ?

R est un langage de programmation 
RStudio est un IDE - Environnement de Programmation Intégré. 
 Passer par R et R studio permet de tout faire un sein de la meme interface. La base de donné se compose, comme dit plus haut,  d'une partie textuelle, résultat d'enquete qualitative traditionnelle, et d'une partie "géomatique/géométrique". R/ RStudio nous permet d'appréhender à la fois le traitement textutel (expresion régulieres ...), les géotraitements (buffer, répartation de géométries...), les représentation graphiques et cartographiques, les statistiques (simples et complexes). 
 Enfin R/Rstudio permettent aussi la programmation lettrée* *(inserer la définition")*.  et donc de produire des documents mise en lignes (document de présentationd ela base de donnée) ou scientifiques, ou universitaires directement à partir des données bruts et des scripts produits (c'est le cas de ce mémoire). 
 
 ### Pourquoi R et pas un autre langage de programmation ? 
 Car il s'agit de l'outil utilisé dans les laboratoire à mon arrivée et qu'il se prete parfaitement à l'analyse statistique et graphique puisu'il a été conçu pour ça. *ref*
 
 