# Méthodologie

> **Contenu central du rapport**

> Il comporte deux ou trois parties (1, 2, 3) subdivisées en deux ou trois sous parties ( 1.1, 1.2, 1.3) tout au plus. En lisant les titres des 4 à 9 sous parties, on doit pouvoir se faire une idée du contenu et de la démarche de l'étude. Le texte est fait pour être lu par une personne qui n'a pas suivi le travail du stagiaire. Un rapport orienté « recherche » intégrera obligatoirement une partie « état de l'art » et valorisera les références bibliographiques.


## La chaine de traitement
Comment avons nous travailler ? 
- Exploration et découverte de la base de donnée
- Control et détection des anomalies avant de rentrer dans les traitements
- Exploration et nettoyage (detection se poursuis)
- Géométries


## Traitement de la base de donnée "géométries"

Possibilité de créer un package pour exploiter les données.\
Pour produire des tableaux à la volée (BDG & BDR) et les gaphiques, cartes, statistiques qui en découlent. Ce travail necessite l'identification précise de productions pour chacun de ces volets (quels graphiques sur quelles données, etc).

la methode

### Géométries et leur classification : enjeux méthodologiques

-   Comparer la superficie du polygone avec la superficie réelle de l'espace décrit (notamment lorsque le mot attribué correspond à cet espace).
-   Quel ordre des polygones pour un même mot donnée
-   Justifier l’intérêt de juger à l’œil (contrôle humain face à la redondance de la tache).
-   Justifier l'usage des menus e leur pertinences vis à vis d'une approche automatisée (identifier les actions automatisables)
    -   Geom repair : intersection
    -   txt move/add : au cas ou mais tres peu utilisé finalement
    -   Typologie : difficle de faire une typologie automatisée (on peut imaginer un scale comme etant une hierarchie des superficie lorsqu'elles sont contenues les unes dans les autres à x%, mais le multi unique et le overlap sont plus complexes car relevent d'une appréciation de l'intention du dessinateur (l'intersection partielle de deux ensemble peut etre due à une imprecision comme à une volonté du dessinateur))

Il reste de nombreuses actons répétitives voire inutiles dans la boucles.

On peut envisager une comparaison des résultats automatisés et manuels

Classification manuelle supervisée (à deux ou trois) pourquoi ? quelle utilité, comment s'organise-t-on pour controler les réponses et les standardiser ?

### La visualisation pour exploration

***Décrire la méthode d'affichage et de classification des polygones puis exposer les problèmes*** ***Présenter les problèmes de géométrie sous forme de shémas / chorème ?***

Problème sémiologiques pour juger rapidement et efficacement dans un premier temps du polygone, puis dans un second temps des choix fait sur ce/ces polygones (contrôle).

Le choix du fond de carte et de sa généralisation posent des enjeux concernant d'une part les polygones décrivant des territoires insulaires qui n'apparaissent pas et d'autre part des polygones décrivant des petits territoires type villes dont on ne peut distinguer les contours.

Dans le premier cas, on visualise un polygone dans un océan sans repères autour (pas d'îles), on peut estimer la justesse du dessin grace aux informations récupérées directement du répondant (le mot associé ou son université d'appartenance surtout) ainsi que par les autres polygones dessinée (lorsqu'il y en a). Surtout ce problème est corrigé en choisissant une échelle de représentation plus fine pour le fond de carte.

Dans le second cas le problème est plus délicat. Il ne s'agit pas d'une niveau de détail du à la généralisation mais à des limites adminstratives ou de toponymes présents ou non pour aider à reconaitre le lieu décrit par le polygone Dans ce cas, choisir un fond de carte plus riche pose d'abord la contrainte de l'alourdissement de la représentation, de la saturation de l'espace visuel au détriment du jugement du polygone (qui est l'objet premier necessitant toute l'attention du visualisateur). Cette option améliore la reconnaissance du lieu décrit par le polygone mais pas à tous les coups. Il peut encore etre necessaire, lorsque la région n'est pas connue, ou encore trop petite de "dézoomer".

L'alternative retenue (dans un premier temps) à été de quitter la boucle d'affichage et de passer par une cartographie interactive des tous les polygones d'un répondant sur une meme carte. Ici le fond de carte est produit par Open Street Map et la généralisation des toponymes et des limites administratives des pays se faut automatique selon le zoom répondant de façon interactive. Ici encore les informations additionnelles données par le répondant sont accessibles pour chacun des polygones via une infobulle générée au clic.

Une autre alternative eu été de directement représenter les polygones via cette carte interactive au sein meme de la boucle.\
Cette option n'a pas encore été explorée.

### Garder ou non les polygones

-   Quel choix pour les **polygones trop petits** : au dessus du quartier ; robleme lors de la représentation (un carreau entier selon la résolution pou une surface potentiellement plus petite que ce carreau)masi ne peut pas etre le seul argument... consider-t-on que quelqu'un entourant "sa maison" répond bien à la question "qu'elle est la zone d'appartenance de votre pays ?". On peut se demadner si la façon dont est posé la question induit cette réponse et donc si elle doit etre disqualiiée ou non. un polygone trop petit pose aussi la question de l'anonymat et de la protection du repondant.

-   Probleme pour les polygones multi-unique et scale, ainsi que over et scale (lorsque les polyhones répondent à plusieurs logiques d'appartenance)

-   Pour les polygones "world" et leur probleme de plot peut-on tous les remplacer par un polygone type ? (plutot non)

-   Que faire des polygones dupliqués

## L'outil : Maptionnaire

### Les biais

#### Systèmes d'exploitation et navigateurs internet pris en charge

> **Does Maptionnaire have any system or browser requirements?** *Maptionnaire uses commercially reasonable efforts to support the two most recent major versions of operating systems with significant market share running up-to-date versions of browsers with significant market share*

> *As of November 9, 2021, the supported operating systems and versions for respondents are:* *- Windows (11, 10)* *- macOS (12, 11)* *- Android (12, 11)* *- iOS/iPadOS (15, 14)*

> *The supported browsers are Chrome, Safari, Firefox, Samsung Internet, Edge, and Opera. For optimal performance, please remember to make sure that you have the latest browser version.\
> If you are part of a team using Maptionnaire to create questionnaires and other content, we recommend that you use the latest version of Chrome.*

Les tables suivantes décrivent l'année de sortie des OS pour les ordinateurs et smartphone.

::: {#tbl-panel .table layout-ncol="2"}
|      WINDOWS      |      MACOS      |
|:-----------------:|:---------------:|
| Windows 10 : 2014 | macOS 11 : 2020 |
| Windows 11 : 2021 | macOS 12 : 2021 |

: Compatibilité ordinateur {#tbl-ordi}

|      Android      |       iOS/iPAD       |
|:-----------------:|:--------------------:|
| Android 11 : 2020 | iOS/iPadOS 14 : 2020 |
| Android 12 : 2022 | iOS/iPadOS 15 : 2021 |

: Compatibilité smartphone {#tbl-phone}

Systèmes d'opération compatibles au 28/06/2022
:::

Comme on peut le voir sur la @tbl-panel, on peut imaginer des problèmes de compatibilité peut etre avec certains parcs informatiques/technologiques possiblement controlable avec des données économiques et de part de marché pour chaque pays. L'application a été massivement *(chiffre etude)*[@bailly2005] utilisée au moyen d'un téléphone, la @tbl-phone nous montre que pour bien fonctionner il faut des téléphones plutot récents, de moins de 2 ans... Ou en tout cas fonctionnant sur un OS récent (de nombreux anciens téléphones peuvent soutenirs de telles mises à jour mais pas tous).[^02_methodologie-1]

[^02_methodologie-1]: Ainsi les téléphone samsugn et Iphone peuvent etre plus performant et mieux mis à jour que des marques moins importantes n'assurant pas la compatibilité au cours du temps. [@noucher2015]

Test de l'application evisageable sur des sites de developpemetn web type "browserStack".

### Les questions

**DROM** On peut supposer que la surreprésenation des droms dans les polygones des français métropolitains est due à la récurrence du terme "DROM" tout au long du questionnaire

**Polygones** La question n'est pas exactement traduite correctement dans chaque langue. Des mot ont été ajouté en allemand par exemple. D'autre part les termes "pays" et "limites" posent des problème d'interprésation (pays = country = campagne ??? - limite = frontiere ???)

## Exploitation de la Base de donnée "Réponses"

-   Explo des données manquantes : VIM ?
    -   distribution des VM (dispositifs et mécanismes)
    -   CAH ou autre pour établir une typologie des NA (profils des répondants)
-   Objectifs de l'enquetes en termes d'effectifs :
    -   5 pays : Tunisie, Turquie, France, Allemagne, Irelande
    -   3 Villes par Pays
    -   240 etudiants par ville
    -   40 etudiants par discipline
