project:
  type: book
  output-dir: docs

book:
  title: "Gestion d'une base de données qualitative et géometrique"
  author: "Elina Marveaux"
  date: "05/12/2022"
  output-file: memoire
  repo-url: https://github.com/ElinaMX/book_memoire
  downloads: pdf
  chapters:
    - index.qmd
    - summary.qmd
    - intro.qmd
    - references.qmd
  appendices: 
    - appendice1.qmd

bibliography: references.bib

format:
  html:
    theme: journal
    echo: false

  pdf:
    echo: false
    documentclass: scrbook
    papersize: a4
    pagestyle: headings
    toc: true
    toc-title: "Table des matières"
    lof: true
    lot: true
    code-line-numbers: true
    fontfamily: accanthis
    highlight-style: github
    keep-tex: true
    include-in-header:
    - header.tex


editor: visual

