project:
  type: book
  output-dir: docs
 
book:
  lang: fr
  title: "Gestion d'une base de données qualitative et géometrique"
  author: "Elina Marveaux"
  date: "12 Juin 2022"
  output-file: memoire
  repo-url: https://github.com/ElinaMX/book_memoire
  chapters:
    - index.qmd
    - antonine.qmd
    - 01_contexte.qmd
    - 02_methodologie.qmd
    - 03_resultats.qmd
    - 04_conclusion.qmd
    - 05a_remerciements.qmd
    - 05b_references.qmd
  appendices: 
    - 06_glossaire.qmd
    - 07_annexes.qmd

bibliography: references.bib

format:
  pdf:
    echo: false
    documentclass: book
    papersize: a4paper
    # classoption: 
    pagestyle: headings
    toc: true
    toc-title: "Table des matières"
    number-depth: 3
    # lof: true
    # lot: true
    fontfamily: gfsartemisia
    # mainfont: Times New Roman
    fontsize: 12pt
    indent: true
    linestretch: 1.5
    highlight-style: solarized 
    code-line-numbers: true
    whitespace: 0pt
    geometry: 
      - heightrounded
      - margin = 25mm
      # - headsep = 05cm
      - headheight = 5cm
      # - includehead = false
      # - ignorehead = true
      - showframe = true
    keep-tex: true
    include-in-header:
      - 00a_header.tex
    include-before-body:
      - _resume.tex
    include-after-body:
      - 00b_backcover.tex

editor: visual

