project:
  type: book
  output-dir: docs

book:
  keywords: 
    - "géomatique"
    - "base de donnée"
    - "cartographie"
  title: "Gestion d'une base de donnée qualitatives et géometrique"
  author: "Elina Marveaux"
  date: "12/05/2022"
  output-file: memoire
  repo-url: https://github.com/ElinaMX/book_memoire
  downloads: pdf
  chapters:
    - index.qmd
    - summary.qmd
    - part: "The Penguins"
      chapters: 
      - part1.qmd
    - intro.qmd
    - part:
    - references.qmd
    - summary.qmd
  appendices: 
    - appendice1.qmd

bibliography: references.bib

format:
  html:
    theme: quartz

  pdf:
    documentclass: scrbook
    papersize: a4
    pagestyle: headings
    toc: true
    toc-title: "Table des matières"
    lof: true
    lot: true
    code-line-numbers: true
    fontfamily: accanthis
    highlight-style: github
    keep-tex: true
    include-in-header:
    - header.Tex


editor: visual

