project:
  type: book
  output-dir: docs

book:
  lang: fr
  title: "Gestion d'une base de données qualitative et géometrique"
  author: "Elina Marveaux"
  date: "12-06-2022"
  output-file: memoire
  repo-url: https://github.com/ElinaMX/book_memoire
  chapters:
    # - summary.qmd
    - index.qmd
    # - intro.qmd
    - antonine.qmd
    - contenu.qmd
    - resultats.qmd
    - conclusion.qmd
    - remerciements.qmd
    - references.qmd
  appendices: 
    - appendice1.qmd

bibliography: references.bib

format:
  pdf:
    echo: false
    documentclass: scrbook
    papersize: a4
    pagestyle: headings
    toc: true
    toc-title: "Table des matières"
    number-depth: 3
    indent: true
    # lof: true
    # lot: true
    code-line-numbers: true
    fontfamily: gfsartemisia
    # fontenc: gfsartemisia
    highlight-style: solarized 
    # interlinespace: |
    #   \setupinterlinespace[line=12pt]
    geometry: 
      - margin = 2.5cm

    keep-tex: true
    linestretch: |
      \onehalfspacing
      
    include-in-header:
      - header.tex
    include-before-body: 
      - 00_resume.qmd
    # include-after-body: 
    


editor: visual

