project:
  type: book
  output-dir: docs

book:
  keywords: 
    - "géomatique"
    - "base de donnée"
    - "cartographie"
  title: "Gestion d'une base de donnée qualitatives et géometrique"
  author: "Elina Marveaux"
  date: "12/05/2022"
  output-file: memoire
  repo-url: https://github.com/ElinaMX/book_memoire
  downloads: pdf
  chapters:
    - index.qmd
    - summary.qmd
    - part: "The Penguins"
      chapters: 
      - part1.qmd
    - intro.qmd
    - part:
    - references.qmd
    - summary.qmd
  appendices: 
    - appendice1.qmd

bibliography: references.bib

format:
  html:
    theme: minty

  pdf:
    documentclass: scrbook
    papersize: a4
    pagestyle: headings
    toc: true
    toc-title: "Table des matières"
    highlight-style: github
    keep-tex: true
    header-includes: |
      \usepackage{titling}
      \setlength{\droptitle}{-2cm}
      \preauthor{
        \begin{center}
        \includegraphics[width=5in,height=4in]{cover.png}\\ % cover figure
        \Large
      }
      \postauthor{
        \end{center}
      }
      \predate{
        \begin{center}
        Master of Science in Biology\\               % Degree
        Biodiversity, Evolution and Ecology\\        % Degree stream
        Department of Biological Sciences\\          % Department
        University of Bergen\\                       % University 
        \vspace{5mm}
      }
      \postdate{
        \\
        \includegraphics[width=1.5in,height=1.5in]{figures/anr-dfg.jpg}\\
        \end{center}
        \newpage
        \mbox{}
        \vfill
        Cover page\\
        \emph{Beckwithia glacialis} on Snøhetta.
       }


editor: visual

